[package]
name = "leetbook"
version = "0.1.0"
description = "LeetBook desktop app"
authors = ["Allen"]
license = "MIT"
edition = "2021"

[lib]
name = "leetbook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"
tiny_http = "0.12"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
